// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organi.Data;

#nullable disable

namespace Organi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Organi.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Organi.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Organi.Models.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Organi.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Organi.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Organi.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaloriesPer100g")
                        .HasColumnType("int");

                    b.Property<double?>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FatPer100g")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("ProteinPer100g")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("ServingSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "İNDİRİM",
                            CaloriesPer100g = 31,
                            CarbsPer100g = 6.0,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4102),
                            Description = "Çiftliğimizden taze organik biber.",
                            FatPer100g = 0.29999999999999999,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Biber",
                            OldPrice = 3.49m,
                            Price = 2.29m,
                            ProteinPer100g = 1.0,
                            Rating = 4.5,
                            RatingCount = 15,
                            ServingSize = "100g",
                            Stock = 50,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 550,
                            CarbsPer100g = 45.0,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4126),
                            Description = "Doğal bitter çikolata.",
                            FatPer100g = 35.0,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Bitter Çikolata",
                            Price = 4.49m,
                            ProteinPer100g = 5.0,
                            Rating = 4.5,
                            RatingCount = 14,
                            ServingSize = "30g",
                            Stock = 30,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 342,
                            CarbsPer100g = 71.0,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4130),
                            Description = "Tam buğday bulguru.",
                            FatPer100g = 1.3,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Bulgur",
                            Price = 2.49m,
                            ProteinPer100g = 12.0,
                            Rating = 4.0,
                            RatingCount = 8,
                            ServingSize = "50g",
                            Stock = 100,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 4,
                            Badge = "HOT",
                            CaloriesPer100g = 654,
                            CarbsPer100g = 14.0,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4132),
                            Description = "Organik iç ceviz 200g.",
                            FatPer100g = 65.200000000000003,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Ceviz",
                            Price = 9.99m,
                            ProteinPer100g = 15.199999999999999,
                            Rating = 4.9000000000000004,
                            RatingCount = 91,
                            ServingSize = "30g porsiyon",
                            Stock = 45,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 5,
                            Badge = "İNDİRİM",
                            CaloriesPer100g = 32,
                            CarbsPer100g = 7.7000000000000002,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4138),
                            Description = "Taze organik çilek.",
                            FatPer100g = 0.29999999999999999,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Çilek",
                            OldPrice = 5.99m,
                            Price = 4.59m,
                            ProteinPer100g = 0.69999999999999996,
                            Rating = 4.5,
                            RatingCount = 30,
                            ServingSize = "100g",
                            Stock = 25,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 52,
                            CarbsPer100g = 14.0,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4141),
                            Description = "Doğal organik elma.",
                            FatPer100g = 0.20000000000000001,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Elma",
                            Price = 2.99m,
                            ProteinPer100g = 0.29999999999999999,
                            Rating = 4.5,
                            RatingCount = 22,
                            ServingSize = "1 adet (150g)",
                            Stock = 80,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 31,
                            CarbsPer100g = 7.0,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4144),
                            Description = "Taze organik yeşil fasulye.",
                            FatPer100g = 0.20000000000000001,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Fasulye",
                            Price = 2.29m,
                            ProteinPer100g = 1.8,
                            Rating = 3.5,
                            RatingCount = 12,
                            ServingSize = "100g",
                            Stock = 60,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 607,
                            CarbsPer100g = 16.0,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4146),
                            Description = "Doğal fındık karışımı.",
                            FatPer100g = 54.0,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Fındık Karışımı",
                            Price = 8.99m,
                            ProteinPer100g = 15.0,
                            Rating = 4.5,
                            RatingCount = 18,
                            ServingSize = "30g",
                            Stock = 40,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 430,
                            CarbsPer100g = 57.0,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4149),
                            Description = "Organik doğal granola bar 40g.",
                            FatPer100g = 15.0,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Granola Bar",
                            Price = 3.99m,
                            ProteinPer100g = 8.4000000000000004,
                            Rating = 4.4000000000000004,
                            RatingCount = 27,
                            ServingSize = "1 bar (45g)",
                            Stock = 100,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 41,
                            CarbsPer100g = 10.0,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4151),
                            Description = "Taze organik havuç.",
                            FatPer100g = 0.20000000000000001,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Havuç",
                            OldPrice = 2.19m,
                            Price = 1.49m,
                            ProteinPer100g = 0.90000000000000002,
                            Rating = 4.0,
                            RatingCount = 19,
                            ServingSize = "100g",
                            Stock = 70,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 241,
                            CarbsPer100g = 63.0,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4154),
                            Description = "Doğal kuru kayısı.",
                            FatPer100g = 0.5,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Organik Kuru Kayısı",
                            Price = 5.49m,
                            ProteinPer100g = 3.3999999999999999,
                            Rating = 4.5,
                            RatingCount = 33,
                            ServingSize = "30g",
                            Stock = 55,
                            Unit = "paket"
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 61,
                            CarbsPer100g = 4.7999999999999998,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 6, 10, 16, 33, 10, 783, DateTimeKind.Local).AddTicks(4156),
                            Description = "Taze organik süt 1 litre.",
                            FatPer100g = 3.2000000000000002,
                            ImageUrl = "/images/placeholder.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Organik Süt",
                            Price = 1.99m,
                            ProteinPer100g = 3.2000000000000002,
                            Rating = 4.7999999999999998,
                            RatingCount = 45,
                            ServingSize = "200ml",
                            Stock = 90,
                            Unit = "litre"
                        });
                });

            modelBuilder.Entity("Organi.Models.Entities.CartItem", b =>
                {
                    b.HasOne("Organi.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Organi.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("Organi.Models.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Organi.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Organi.Models.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
